# Generated by Django 2.2.24 on 2021-12-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='carted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('Beverage', 'Beverage'), ('Dairy_products', 'Dairy_products')], max_length=200),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
