# Generated by Django 4.0 on 2021-12-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_shop', '0003_auto_20211223_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='required_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
