# Generated by Django 4.0 on 2021-12-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_shop', '0005_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('Beverage', 'Beverage'), ('Dairy_products', 'Dairy_products'), ('Snacks', 'Snacks')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
